/**
 * Mock marketplace data — Phase 2.
 * Generated by scripts/gen-marketplace-mock.mjs. Edit the generator, not this
 * file. Images are Lorem Picsum (free, Unsplash-sourced); videos are the
 * Pexels-License clips in /public/media. Swap for real data via the API layer.
 */

export type MediaType = "image" | "video";

export interface Piece {
  id: string;
  type: MediaType;
  title: string;
  category: string;
  width: number;
  height: number;
  durationSec?: number;
  posterUrl: string;
  lqip: string;
  mediaUrl: string;
  watermarked: boolean;
  status: "available" | "sold" | "pending";
  stats: {
    views: number;
    comments: number;
    likes: number;
    bookmarks: number;
    inspired: number;
  };
  creator: { handle: string; avatarUrl: string };
}

export interface MkCategory {
  name: string;
  label: string;
  count: number;
}

export const MOCK_TOTAL = 10559;

export const MOCK_CATEGORIES: MkCategory[] = [
  {
    "name": "fantasy",
    "label": "Fantasy",
    "count": 1314
  },
  {
    "name": "landscapes",
    "label": "Landscapes",
    "count": 1451
  },
  {
    "name": "portraits",
    "label": "Portraits",
    "count": 2278
  },
  {
    "name": "anime",
    "label": "Anime",
    "count": 751
  },
  {
    "name": "animals",
    "label": "Animals",
    "count": 1242
  },
  {
    "name": "sci-fi",
    "label": "Sci-Fi",
    "count": 1964
  },
  {
    "name": "fashion",
    "label": "Fashion",
    "count": 1057
  },
  {
    "name": "food",
    "label": "Food",
    "count": 502
  }
];

export const MOCK_PIECES: Piece[] = [
  {
    "id": "img-aur01",
    "type": "image",
    "title": "Fantasy",
    "category": "fantasy",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur01.jpg",
    "lqip": "/marketplace/img/aur01-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur01.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 12000,
      "comments": 0,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 8000
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur02",
    "type": "image",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur02.jpg",
    "lqip": "/marketplace/img/aur02-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur02.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 7000,
      "comments": 3,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 8317
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur03",
    "type": "image",
    "title": "Portraits",
    "category": "portraits",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur03.jpg",
    "lqip": "/marketplace/img/aur03-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur03.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 17000,
      "comments": 1,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 8634
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur04",
    "type": "image",
    "title": "Anime",
    "category": "anime",
    "width": 1216,
    "height": 832,
    "posterUrl": "/marketplace/img/aur04.jpg",
    "lqip": "/marketplace/img/aur04-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur04.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 8500,
      "comments": 4,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 8951
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur05",
    "type": "image",
    "title": "Animals",
    "category": "animals",
    "width": 1280,
    "height": 800,
    "posterUrl": "/marketplace/img/aur05.jpg",
    "lqip": "/marketplace/img/aur05-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur05.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 6800,
      "comments": 2,
      "likes": 4,
      "bookmarks": 1,
      "inspired": 9268
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-ocean",
    "type": "video",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/hero-ocean.jpg",
    "lqip": "/media/hero-ocean.jpg",
    "mediaUrl": "/media/hero-ocean.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1800,
      "comments": 4,
      "likes": 4,
      "bookmarks": 1,
      "inspired": 16876
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur06",
    "type": "image",
    "title": "Sci-Fi",
    "category": "sci-fi",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur06.jpg",
    "lqip": "/marketplace/img/aur06-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur06.jpg",
    "watermarked": true,
    "status": "sold",
    "stats": {
      "views": 7500,
      "comments": 0,
      "likes": 5,
      "bookmarks": 2,
      "inspired": 9585
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur07",
    "type": "image",
    "title": "Fashion",
    "category": "fashion",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur07.jpg",
    "lqip": "/marketplace/img/aur07-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur07.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 7200,
      "comments": 3,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 9902
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur08",
    "type": "image",
    "title": "Food",
    "category": "food",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur08.jpg",
    "lqip": "/marketplace/img/aur08-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur08.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1100,
      "comments": 1,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 10219
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur09",
    "type": "image",
    "title": "Fantasy",
    "category": "fantasy",
    "width": 1216,
    "height": 832,
    "posterUrl": "/marketplace/img/aur09.jpg",
    "lqip": "/marketplace/img/aur09-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur09.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 4800,
      "comments": 4,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 10536
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur10",
    "type": "image",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 1280,
    "height": 800,
    "posterUrl": "/marketplace/img/aur10.jpg",
    "lqip": "/marketplace/img/aur10-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur10.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 983,
      "comments": 2,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 10853
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-forest",
    "type": "video",
    "title": "Fantasy",
    "category": "fantasy",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/hero-forest.jpg",
    "lqip": "/media/hero-forest.jpg",
    "mediaUrl": "/media/hero-forest.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1600,
      "comments": 2,
      "likes": 5,
      "bookmarks": 2,
      "inspired": 17193
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur11",
    "type": "image",
    "title": "Portraits",
    "category": "portraits",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur11.jpg",
    "lqip": "/marketplace/img/aur11-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur11.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1800,
      "comments": 0,
      "likes": 4,
      "bookmarks": 1,
      "inspired": 11170
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur12",
    "type": "image",
    "title": "Anime",
    "category": "anime",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur12.jpg",
    "lqip": "/marketplace/img/aur12-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur12.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1600,
      "comments": 3,
      "likes": 5,
      "bookmarks": 2,
      "inspired": 11487
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur13",
    "type": "image",
    "title": "Animals",
    "category": "animals",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur13.jpg",
    "lqip": "/marketplace/img/aur13-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur13.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 625,
      "comments": 1,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 11804
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur14",
    "type": "image",
    "title": "Sci-Fi",
    "category": "sci-fi",
    "width": 1216,
    "height": 832,
    "posterUrl": "/marketplace/img/aur14.jpg",
    "lqip": "/marketplace/img/aur14-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur14.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 748,
      "comments": 4,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 12121
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur15",
    "type": "image",
    "title": "Fashion",
    "category": "fashion",
    "width": 1280,
    "height": 800,
    "posterUrl": "/marketplace/img/aur15.jpg",
    "lqip": "/marketplace/img/aur15-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur15.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1200,
      "comments": 2,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 12438
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-coast",
    "type": "video",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/hero-coast.jpg",
    "lqip": "/media/hero-coast.jpg",
    "mediaUrl": "/media/hero-coast.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 625,
      "comments": 0,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 17510
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur16",
    "type": "image",
    "title": "Food",
    "category": "food",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur16.jpg",
    "lqip": "/marketplace/img/aur16-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur16.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 913,
      "comments": 0,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 12755
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur17",
    "type": "image",
    "title": "Fantasy",
    "category": "fantasy",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur17.jpg",
    "lqip": "/marketplace/img/aur17-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur17.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 14000,
      "comments": 3,
      "likes": 4,
      "bookmarks": 1,
      "inspired": 13072
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur18",
    "type": "image",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur18.jpg",
    "lqip": "/marketplace/img/aur18-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur18.jpg",
    "watermarked": true,
    "status": "sold",
    "stats": {
      "views": 1300,
      "comments": 1,
      "likes": 5,
      "bookmarks": 2,
      "inspired": 13389
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur19",
    "type": "image",
    "title": "Portraits",
    "category": "portraits",
    "width": 1216,
    "height": 832,
    "posterUrl": "/marketplace/img/aur19.jpg",
    "lqip": "/marketplace/img/aur19-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur19.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 12000,
      "comments": 4,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 13706
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur20",
    "type": "image",
    "title": "Anime",
    "category": "anime",
    "width": 1280,
    "height": 800,
    "posterUrl": "/marketplace/img/aur20.jpg",
    "lqip": "/marketplace/img/aur20-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur20.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 7000,
      "comments": 2,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 14023
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-city",
    "type": "video",
    "title": "Sci-Fi",
    "category": "sci-fi",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/hero-city.jpg",
    "lqip": "/media/hero-city.jpg",
    "mediaUrl": "/media/hero-city.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 748,
      "comments": 3,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 17827
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur21",
    "type": "image",
    "title": "Animals",
    "category": "animals",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur21.jpg",
    "lqip": "/marketplace/img/aur21-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur21.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 17000,
      "comments": 0,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 14340
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur22",
    "type": "image",
    "title": "Sci-Fi",
    "category": "sci-fi",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur22.jpg",
    "lqip": "/marketplace/img/aur22-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur22.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 8500,
      "comments": 3,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 14657
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur23",
    "type": "image",
    "title": "Fashion",
    "category": "fashion",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur23.jpg",
    "lqip": "/marketplace/img/aur23-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur23.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 6800,
      "comments": 1,
      "likes": 4,
      "bookmarks": 1,
      "inspired": 14974
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur24",
    "type": "image",
    "title": "Food",
    "category": "food",
    "width": 1216,
    "height": 832,
    "posterUrl": "/marketplace/img/aur24.jpg",
    "lqip": "/marketplace/img/aur24-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur24.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 7500,
      "comments": 4,
      "likes": 5,
      "bookmarks": 2,
      "inspired": 15291
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur25",
    "type": "image",
    "title": "Fantasy",
    "category": "fantasy",
    "width": 1280,
    "height": 800,
    "posterUrl": "/marketplace/img/aur25.jpg",
    "lqip": "/marketplace/img/aur25-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur25.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 7200,
      "comments": 2,
      "likes": 0,
      "bookmarks": 0,
      "inspired": 15608
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-ink",
    "type": "video",
    "title": "Anime",
    "category": "anime",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/generate-ink.jpg",
    "lqip": "/media/generate-ink.jpg",
    "mediaUrl": "/media/generate-ink.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1200,
      "comments": 1,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 18144
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur26",
    "type": "image",
    "title": "Landscapes",
    "category": "landscapes",
    "width": 832,
    "height": 1216,
    "posterUrl": "/marketplace/img/aur26.jpg",
    "lqip": "/marketplace/img/aur26-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur26.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 1100,
      "comments": 0,
      "likes": 1,
      "bookmarks": 1,
      "inspired": 15925
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur27",
    "type": "image",
    "title": "Portraits",
    "category": "portraits",
    "width": 768,
    "height": 1280,
    "posterUrl": "/marketplace/img/aur27.jpg",
    "lqip": "/marketplace/img/aur27-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur27.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 4800,
      "comments": 3,
      "likes": 2,
      "bookmarks": 2,
      "inspired": 16242
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "img-aur28",
    "type": "image",
    "title": "Anime",
    "category": "anime",
    "width": 1024,
    "height": 1024,
    "posterUrl": "/marketplace/img/aur28.jpg",
    "lqip": "/marketplace/img/aur28-lqip.jpg",
    "mediaUrl": "/marketplace/img/aur28.jpg",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 983,
      "comments": 1,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 16559
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  },
  {
    "id": "vid-neon",
    "type": "video",
    "title": "Sci-Fi",
    "category": "sci-fi",
    "width": 1280,
    "height": 720,
    "durationSec": 12,
    "posterUrl": "/media/edit-neon.jpg",
    "lqip": "/media/edit-neon.jpg",
    "mediaUrl": "/media/edit-neon.mp4",
    "watermarked": true,
    "status": "available",
    "stats": {
      "views": 913,
      "comments": 4,
      "likes": 3,
      "bookmarks": 0,
      "inspired": 18461
    },
    "creator": {
      "handle": "@aurora",
      "avatarUrl": ""
    }
  }
];
